// Predefined source catalogue — templates users can instantiate as sources
const CATALOGUE = [
    {
        id: 'jellyfin',
        name: 'Jellyfin',
        description: 'Jellyfin media server (requires webhook plugin)',
        eventTypePaths: ['NotificationType'],
        knownEvents: [
            'ItemAdded', 'ItemDeleted',
            'PlaybackStart', 'PlaybackProgress', 'PlaybackStop',
            'UserCreated', 'UserDeleted', 'UserLockedOut', 'UserPasswordChanged',
            'AuthenticationSuccess', 'AuthenticationFailure',
            'SessionStart', 'TaskCompleted',
            'PluginInstalled', 'PluginUpdated', 'PluginUninstalled',
        ],
        sampleTokenPaths: [
            'NotificationType', 'ServerName', 'ServerUrl',
            'Name', 'ItemType', 'Year', 'Overview',
            'SeriesName', 'SeasonNumber', 'EpisodeNumber',
            'NotificationUsername', 'DeviceName', 'ClientName',
            'PlayMethod', 'PlaybackPosition',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'NotificationType', desc: 'Event type' },
                { token: 'ServerName',       desc: 'Jellyfin server name' },
                { token: 'ServerUrl',        desc: 'Jellyfin server URL' },
            ],
            'Playback': [
                { token: 'Name',             desc: 'Item title' },
                { token: 'ItemType',         desc: 'Movie / Episode / Audio etc.' },
                { token: 'Year',             desc: 'Release year' },
                { token: 'Overview',         desc: 'Synopsis' },
                { token: 'SeriesName',       desc: 'Series name (TV)' },
                { token: 'SeasonNumber',     desc: 'Season number' },
                { token: 'EpisodeNumber',    desc: 'Episode number' },
                { token: 'NotificationUsername', desc: 'User who triggered event' },
                { token: 'DeviceName',       desc: 'Playback device' },
                { token: 'ClientName',       desc: 'Client app name' },
                { token: 'PlayMethod',       desc: 'DirectPlay / Transcode / DirectStream' },
                { token: 'PlaybackPosition', desc: 'Current position' },
            ],
            'User events': [
                { token: 'NotificationUsername', desc: 'Affected username' },
            ],
            'Plugin events': [
                { token: 'Name',    desc: 'Plugin name' },
                { token: 'Version', desc: 'Plugin version' },
            ],
            'Task events': [
                { token: 'Name',   desc: 'Task name' },
                { token: 'Status', desc: 'Task result status' },
            ],
        },
    },
    {
        id: 'plex',
        name: 'Plex',
        description: 'Plex Media Server (requires Plex Pass)',
        eventTypePaths: ['event'],
        knownEvents: [
            'media.play', 'media.pause', 'media.resume', 'media.stop',
            'media.scrobble', 'media.rate', 'library.new', 'library.on.deck',
        ],
        sampleTokenPaths: [
            'event',
            'Account.title', 'Account.thumb',
            'Server.title',
            'Player.title', 'Player.platform',
            'Metadata.type', 'Metadata.title', 'Metadata.grandparentTitle',
            'Metadata.parentTitle', 'Metadata.index', 'Metadata.parentIndex',
            'Metadata.year', 'Metadata.summary', 'Metadata.rating',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'event',              desc: 'Event type (media.play, library.new, etc.)' },
                { token: 'Account.title',      desc: 'Plex account username' },
                { token: 'Account.thumb',      desc: 'Account avatar URL' },
                { token: 'Server.title',       desc: 'Plex server name' },
            ],
            'library.new / library.on.deck': [
                { token: 'Metadata.type',                    desc: 'movie / episode / track' },
                { token: 'Metadata.title',                   desc: 'Item title (episode title for TV)' },
                { token: 'Metadata.grandparentTitle',        desc: 'Series name (TV)' },
                { token: 'Metadata.parentTitle',             desc: 'Season name (TV)' },
                { token: 'Metadata.index',                   desc: 'Episode number' },
                { token: 'Metadata.parentIndex',             desc: 'Season number' },
                { token: 'Metadata.year',                    desc: 'Release year' },
                { token: 'Metadata.summary',                 desc: 'Synopsis' },
                { token: 'Metadata.contentRating',           desc: 'Content rating (e.g. TV-MA, PG-13)' },
                { token: 'Metadata.audienceRating',          desc: 'Audience rating (e.g. 7.9)' },
                { token: 'Metadata.originallyAvailableAt',   desc: 'Original air/release date' },
                { token: 'Metadata.thumb',                   desc: 'Episode/item thumbnail — local server path, not usable in email' },
                { token: 'Metadata.grandparentThumb',        desc: 'Series poster — local server path, not usable in email' },
            ],
            'Playback events': [
                { token: 'Player.title',              desc: 'Player device name' },
                { token: 'Player.platform',           desc: 'Player platform (iOS, Roku, etc.)' },
                { token: 'Metadata.type',             desc: 'movie / episode / track' },
                { token: 'Metadata.title',            desc: 'Item title' },
                { token: 'Metadata.grandparentTitle', desc: 'Series name (TV)' },
                { token: 'Metadata.parentTitle',      desc: 'Season name (TV)' },
                { token: 'Metadata.index',            desc: 'Episode number' },
                { token: 'Metadata.parentIndex',      desc: 'Season number' },
                { token: 'Metadata.year',             desc: 'Release year' },
                { token: 'Metadata.summary',          desc: 'Synopsis' },
                { token: 'Metadata.rating',           desc: 'Content rating' },
            ],
        },
    },
    {
        id: 'prowlarr',
        name: 'Prowlarr',
        description: 'Indexer management',
        eventTypePaths: ['eventType'],
        knownEvents: ['Test', 'Health', 'HealthRestored', 'ApplicationUpdate'],
        sampleTokenPaths: [
            'eventType', 'instanceName', 'applicationUrl',
            'level', 'message', 'type', 'wikiUrl',
            'previousVersion', 'newVersion',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'eventType',       desc: 'Event type' },
                { token: 'instanceName',    desc: 'Prowlarr instance name' },
                { token: 'applicationUrl',  desc: 'Prowlarr base URL' },
            ],
            'Health / HealthRestored': [
                { token: 'level',    desc: 'Warning or Error' },
                { token: 'message',  desc: 'Health check message' },
                { token: 'type',     desc: 'Check type' },
                { token: 'wikiUrl',  desc: 'Wiki link for this issue' },
            ],
            'ApplicationUpdate': [
                { token: 'message',         desc: 'Update message' },
                { token: 'previousVersion', desc: 'Version before update' },
                { token: 'newVersion',      desc: 'Version after update' },
            ],
        },
    },
    {
        id: 'radarr',
        name: 'Radarr',
        description: 'Movie download & management',
        eventTypePaths: ['eventType'],
        knownEvents: [
            'Test', 'Grab', 'Download', 'Rename', 'MovieAdded', 'MovieDelete',
            'MovieFileDelete', 'Health', 'HealthRestored', 'ApplicationUpdate',
        ],
        sampleTokenPaths: [
            'eventType', 'instanceName', 'applicationUrl',
            'movie.title', 'movie.year', 'movie.imdbId', 'movie.tmdbId',
            'movie.overview', 'movie.rating', 'movie.inCinemas', 'movie.physicalRelease',
            'movie.path', 'movie.folderPath',
            'movie.posterUrl', 'movie.fanartUrl',
            'release.quality', 'release.size', 'release.releaseTitle',
            'release.releaseGroup', 'release.indexer',
            'movieFile.quality', 'movieFile.size', 'movieFile.path', 'movieFile.releaseGroup',
            'downloadClient', 'downloadClientType', 'downloadId',
            'isUpgrade',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'eventType',       desc: 'Event type (Grab, Download, etc.)' },
                { token: 'instanceName',    desc: 'Radarr instance name' },
                { token: 'applicationUrl',  desc: 'Radarr base URL' },
                { token: 'movie.title',     desc: 'Movie title' },
                { token: 'movie.year',      desc: 'Release year' },
                { token: 'movie.imdbId',    desc: 'IMDb ID' },
                { token: 'movie.tmdbId',    desc: 'TMDB ID' },
                { token: 'movie.overview',  desc: 'Movie synopsis' },
                { token: 'movie.rating',    desc: 'Audience rating' },
                { token: 'movie.path',      desc: 'Library path' },
                { token: 'movie.posterUrl', desc: 'Poster image URL' },
                { token: 'movie.bannerUrl', desc: 'Banner image URL' },
                { token: 'movie.fanartUrl', desc: 'Fanart image URL' },
            ],
            'Grab': [
                { token: 'release.quality',      desc: 'Quality profile (e.g. Bluray-1080p)' },
                { token: 'release.size',         desc: 'Release size in bytes' },
                { token: 'release.releaseTitle', desc: 'Full release name' },
                { token: 'release.releaseGroup', desc: 'Release group' },
                { token: 'release.indexer',      desc: 'Indexer used' },
                { token: 'downloadClient',       desc: 'Download client name' },
                { token: 'downloadClientType',   desc: 'Download client type' },
                { token: 'downloadId',           desc: 'Download task ID' },
            ],
            'Download': [
                { token: 'movieFile.quality',        desc: 'File quality profile' },
                { token: 'movieFile.size',           desc: 'File size in bytes' },
                { token: 'movieFile.sizeFormatted',  desc: 'File size (formatted, e.g. 2.09 GB)' },
                { token: 'movieFile.path',           desc: 'Full file path on disk' },
                { token: 'movieFile.releaseGroup',   desc: 'Release group' },
                { token: 'isUpgrade',                desc: 'true if this replaced an existing file' },
                { token: 'downloadClient',           desc: 'Download client name' },
            ],
            'MovieAdded': [
                { token: 'movie.title',           desc: 'Movie title' },
                { token: 'movie.year',            desc: 'Release year' },
                { token: 'movie.tmdbId',          desc: 'TMDB ID' },
                { token: 'movie.folderPath',      desc: 'Destination folder' },
                { token: 'movie.inCinemas',       desc: 'Cinema release date' },
                { token: 'movie.physicalRelease', desc: 'Physical / digital release date' },
            ],
            'MovieDelete': [
                { token: 'movie.title',    desc: 'Movie title' },
                { token: 'movie.year',     desc: 'Release year' },
                { token: 'deleteReason',   desc: 'Reason for deletion' },
            ],
            'MovieFileDelete': [
                { token: 'movie.title',            desc: 'Movie title' },
                { token: 'movieFile.path',         desc: 'Deleted file path' },
                { token: 'movieFile.quality',      desc: 'File quality' },
                { token: 'deleteReason',           desc: 'Reason for deletion' },
            ],
            'Rename': [
                { token: 'movie.title',  desc: 'Movie title' },
                { token: 'movie.path',   desc: 'Library path' },
            ],
            'Health / HealthRestored': [
                { token: 'level',    desc: 'Warning or Error' },
                { token: 'message',  desc: 'Health check message' },
                { token: 'type',     desc: 'Check type' },
                { token: 'wikiUrl',  desc: 'Wiki link for this issue' },
            ],
            'ApplicationUpdate': [
                { token: 'message',         desc: 'Update message' },
                { token: 'previousVersion', desc: 'Version before update' },
                { token: 'newVersion',      desc: 'Version after update' },
            ],
        },
    },
    {
        id: 'overseerr',
        name: 'Seerr',
        description: 'Media request management (Seerr / Overseerr)',
        eventTypePaths: ['notification_type'],
        knownEvents: [
            'TEST_NOTIFICATION', 'MEDIA_PENDING', 'MEDIA_APPROVED', 'MEDIA_AVAILABLE',
            'MEDIA_FAILED', 'MEDIA_DECLINED', 'MEDIA_AUTO_APPROVED',
            'ISSUE_CREATED', 'ISSUE_COMMENT', 'ISSUE_RESOLVED', 'ISSUE_REOPENED',
        ],
        sampleTokenPaths: [
            'notification_type', 'subject', 'message',
            'media.media_type', 'media.tmdbId', 'media.tvdbId', 'media.status',
            'media.imdb_url', 'media.tmdb_url',
            'request.requestedBy_username', 'request.requestedBy_email',
            'request.requestedBy_avatar', 'request.requestCount',
            'issue.issue_type', 'issue.issue_status', 'issue.reportedBy_username',
            'issue.comment_message',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'notification_type', desc: 'Event type (MEDIA_PENDING, etc.)' },
                { token: 'subject',           desc: 'Notification subject line' },
                { token: 'message',           desc: 'Notification body message' },
            ],
            'Media events': [
                { token: 'media.media_type',  desc: 'movie or tv' },
                { token: 'media.tmdbId',      desc: 'TMDB ID' },
                { token: 'media.tvdbId',      desc: 'TVDB ID (TV only)' },
                { token: 'media.status',      desc: 'Request status' },
                { token: 'media.imdb_url',    desc: 'IMDb page URL' },
                { token: 'media.tmdb_url',    desc: 'TMDB page URL' },
            ],
            'Request events': [
                { token: 'request.requestedBy_username', desc: 'Requesting user' },
                { token: 'request.requestedBy_email',    desc: 'Requesting user email' },
                { token: 'request.requestedBy_avatar',   desc: 'Requesting user avatar URL' },
                { token: 'request.requestCount',         desc: 'Total requests by this user' },
            ],
            'Issue events': [
                { token: 'issue.issue_type',          desc: 'Issue category' },
                { token: 'issue.issue_status',        desc: 'open / resolved' },
                { token: 'issue.reportedBy_username', desc: 'Reporter username' },
                { token: 'issue.comment_message',     desc: 'Comment text (ISSUE_COMMENT)' },
            ],
        },
    },
    {
        id: 'sonarr',
        name: 'Sonarr',
        description: 'TV series download & management',
        eventTypePaths: ['eventType'],
        knownEvents: [
            'Test', 'Grab', 'Download', 'Rename', 'SeriesAdd', 'SeriesDelete',
            'EpisodeFileDelete', 'Health', 'HealthRestored', 'ApplicationUpdate',
        ],
        sampleTokenPaths: [
            'eventType', 'instanceName', 'applicationUrl',
            'series.title', 'series.year', 'series.network', 'series.type',
            'series.path', 'series.tvdbId', 'series.imdbId', 'series.tmdbId',
            'series.posterUrl', 'series.bannerUrl', 'series.fanartUrl',
            'episodes[0].title', 'episodes[0].overview',
            'episodes[0].seasonNumber', 'episodes[0].episodeNumber',
            'episodes[0].airDate', 'episodes[0].airDateUtc',
            'release.quality', 'release.sizeFormatted', 'release.releaseTitle',
            'release.releaseGroup', 'release.indexer',
            'episodeFiles[0].quality', 'episodeFiles[0].sizeFormatted',
            'episodeFiles[0].releaseGroup', 'episodeFiles[0].path',
            'downloadClient', 'downloadClientType', 'downloadId',
            'isUpgrade',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'eventType',         desc: 'Event type (Grab, Download, etc.)' },
                { token: 'instanceName',      desc: 'Sonarr instance name' },
                { token: 'applicationUrl',    desc: 'Sonarr base URL' },
                { token: 'series.title',      desc: 'Series title' },
                { token: 'series.year',       desc: 'Series start year' },
                { token: 'series.type',       desc: 'standard / anime / daily' },
                { token: 'series.path',       desc: 'Library path' },
                { token: 'series.network',    desc: 'Broadcast network' },
                { token: 'series.tvdbId',     desc: 'TVDB ID' },
                { token: 'series.imdbId',     desc: 'IMDb ID' },
                { token: 'series.tmdbId',     desc: 'TMDB ID' },
                { token: 'series.posterUrl',  desc: 'Poster image URL' },
                { token: 'series.bannerUrl',  desc: 'Banner image URL' },
                { token: 'series.fanartUrl',  desc: 'Fanart image URL' },
            ],
            'Grab': [
                { token: 'episodes[0].title',                desc: 'Episode title' },
                { token: 'episodes[0].overview',             desc: 'Episode synopsis' },
                { token: 'episodes[0].seasonNumber',         desc: 'Season number' },
                { token: 'episodes[0].seasonNumberPadded',   desc: 'Season number zero-padded (e.g. 07)' },
                { token: 'episodes[0].episodeNumber',        desc: 'Episode number' },
                { token: 'episodes[0].episodeNumberPadded',  desc: 'Episode number zero-padded (e.g. 07)' },
                { token: 'episodes[0].airDate',              desc: 'Air date (YYYY-MM-DD)' },
                { token: 'release.quality',           desc: 'Quality profile (e.g. WEBDL-720p)' },
                { token: 'release.sizeFormatted',     desc: 'Release size (formatted, e.g. 2.09 GB)' },
                { token: 'release.releaseTitle',      desc: 'Full release name' },
                { token: 'release.releaseGroup',      desc: 'Release group' },
                { token: 'release.indexer',           desc: 'Indexer used' },
                { token: 'downloadClient',            desc: 'Download client name' },
                { token: 'downloadClientType',        desc: 'Download client type' },
                { token: 'downloadId',                desc: 'Download task ID' },
            ],
            'Download': [
                { token: 'episodes[0].title',                desc: 'Episode title' },
                { token: 'episodes[0].overview',             desc: 'Episode synopsis' },
                { token: 'episodes[0].seasonNumber',         desc: 'Season number' },
                { token: 'episodes[0].seasonNumberPadded',   desc: 'Season number zero-padded (e.g. 07)' },
                { token: 'episodes[0].episodeNumber',        desc: 'Episode number' },
                { token: 'episodes[0].episodeNumberPadded',  desc: 'Episode number zero-padded (e.g. 07)' },
                { token: 'episodes[0].airDate',              desc: 'Air date (YYYY-MM-DD)' },
                { token: 'episodeFiles[0].quality',          desc: 'File quality profile' },
                { token: 'episodeFiles[0].sizeFormatted',    desc: 'File size (formatted, e.g. 2.09 GB)' },
                { token: 'episodeFiles[0].releaseGroup',     desc: 'Release group' },
                { token: 'episodeFiles[0].path',             desc: 'Full file path on disk' },
                { token: 'isUpgrade',                        desc: 'true if this replaced an existing file' },
                { token: 'downloadClient',                   desc: 'Download client name' },
            ],
            'SeriesAdd': [
                { token: 'series.title',   desc: 'Series title' },
                { token: 'series.year',    desc: 'Series start year' },
                { token: 'series.tvdbId',  desc: 'TVDB ID' },
                { token: 'series.path',    desc: 'Library path' },
                { token: 'series.network', desc: 'Broadcast network' },
            ],
            'SeriesDelete': [
                { token: 'series.title',  desc: 'Series title' },
                { token: 'deleteReason',  desc: 'Reason for deletion' },
            ],
            'EpisodeFileDelete': [
                { token: 'episodes[0].title',                desc: 'Episode title' },
                { token: 'episodes[0].seasonNumber',         desc: 'Season number' },
                { token: 'episodes[0].seasonNumberPadded',   desc: 'Season number zero-padded (e.g. 07)' },
                { token: 'episodes[0].episodeNumber',        desc: 'Episode number' },
                { token: 'episodes[0].episodeNumberPadded',  desc: 'Episode number zero-padded (e.g. 07)' },
                { token: 'episodeFiles[0].path',             desc: 'Deleted file path' },
                { token: 'episodeFiles[0].quality',          desc: 'File quality' },
                { token: 'episodeFiles[0].sizeFormatted',    desc: 'File size (formatted, e.g. 2.09 GB)' },
                { token: 'deleteReason',                     desc: 'Reason for deletion' },
            ],
            'Rename': [
                { token: 'series.title', desc: 'Series title' },
                { token: 'series.path',  desc: 'Library path' },
            ],
            'Health / HealthRestored': [
                { token: 'level',    desc: 'Warning or Error' },
                { token: 'message',  desc: 'Health check message' },
                { token: 'type',     desc: 'Check type' },
                { token: 'wikiUrl',  desc: 'Wiki link for this issue' },
            ],
            'ApplicationUpdate': [
                { token: 'message',         desc: 'Update message' },
                { token: 'previousVersion', desc: 'Version before update' },
                { token: 'newVersion',      desc: 'Version after update' },
            ],
        },
    },
    {
        id: 'tautulli',
        name: 'Tautulli',
        description: 'Plex Media Server monitoring',
        eventTypePaths: ['action'],
        knownEvents: [
            'play', 'stop', 'pause', 'resume', 'watched',
            'created', 'recently_added', 'transcode_decision_change',
        ],
        sampleTokenPaths: [
            'action', 'title', 'grandparent_title', 'parent_title',
            'media_type', 'year', 'summary', 'rating',
            'user', 'user_email', 'player',
            'quality_profile', 'stream_duration', 'progress_percent',
            'season_num', 'episode_num', 'studio', 'genres',
            'thumb', 'art',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'action',     desc: 'Event type (play, stop, etc.)' },
                { token: 'media_type', desc: 'movie / episode / track / photo' },
                { token: 'title',      desc: 'Item title' },
                { token: 'year',       desc: 'Release year' },
                { token: 'summary',    desc: 'Synopsis' },
                { token: 'rating',     desc: 'Content rating' },
                { token: 'thumb',      desc: 'Poster/thumbnail URL' },
                { token: 'art',        desc: 'Background art URL' },
            ],
            'TV specific': [
                { token: 'grandparent_title', desc: 'Series name' },
                { token: 'parent_title',      desc: 'Season name' },
                { token: 'season_num',        desc: 'Season number' },
                { token: 'episode_num',       desc: 'Episode number' },
            ],
            'Playback': [
                { token: 'user',              desc: 'Plex username' },
                { token: 'user_email',        desc: 'User email' },
                { token: 'player',            desc: 'Player device name' },
                { token: 'quality_profile',   desc: 'Stream quality' },
                { token: 'stream_duration',   desc: 'Stream duration (seconds)' },
                { token: 'progress_percent',  desc: 'Playback progress %' },
            ],
        },
    },
    {
        id: 'uptimekuma',
        name: 'Uptime Kuma',
        description: 'Self-hosted uptime monitoring',
        eventTypePaths: ['heartbeat.status'],
        knownEvents: ['0', '1'],
        sampleTokenPaths: [
            'heartbeat.status', 'heartbeat.msg', 'heartbeat.time',
            'heartbeat.duration', 'heartbeat.retries',
            'monitor.name', 'monitor.url', 'monitor.type',
            'monitor.interval', 'monitor.hostname', 'monitor.port',
            'msg',
        ],
        eventTokenMap: {
            'All events': [
                { token: 'msg',                desc: 'Full status message' },
                { token: 'heartbeat.status',   desc: '0 = down, 1 = up' },
                { token: 'heartbeat.msg',      desc: 'Status message' },
                { token: 'heartbeat.time',     desc: 'Timestamp of check' },
                { token: 'heartbeat.duration', desc: 'Response time (ms)' },
                { token: 'heartbeat.retries',  desc: 'Retry count before alert' },
            ],
            'Monitor': [
                { token: 'monitor.name',     desc: 'Monitor display name' },
                { token: 'monitor.url',      desc: 'Monitored URL' },
                { token: 'monitor.type',     desc: 'http / tcp / ping / dns etc.' },
                { token: 'monitor.interval', desc: 'Check interval (seconds)' },
                { token: 'monitor.hostname', desc: 'Hostname (TCP/ping monitors)' },
                { token: 'monitor.port',     desc: 'Port (TCP monitors)' },
            ],
        },
    },
    {
        id: 'custom',
        name: 'Custom',
        description: 'Generic webhook source',
        eventTypePaths: ['eventType', 'event', 'type', 'action'],
        knownEvents: [],
        sampleTokenPaths: [],
    },
];

function getCatalogueEntries() {
    return CATALOGUE
        .map(({ id, name, description, knownEvents }) => ({ id, name, description, knownEvents }))
        .sort((a, b) => {
            if (a.id === 'custom') return 1;
            if (b.id === 'custom') return -1;
            return a.name.localeCompare(b.name);
        });
}

function getCatalogueEntry(id) {
    return CATALOGUE.find(e => e.id === id) || null;
}

module.exports = { getCatalogueEntries, getCatalogueEntry };
